// Run from the repository root: bun scripts/generate-app-icon.ts [--check]
// Bun and librsvg (rsvg-convert) are only needed to regenerate the artwork.
// App builds copy the committed .icns and do not need either tool.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { fishArt } from "../site/lib/art";
import { tea } from "../site/lib/ink";

const args = process.argv.slice(2);
if (args.length > 1 || args.some((arg) => arg !== "--check")) {
  throw new Error("Usage: bun scripts/generate-app-icon.ts [--check]");
}
if (process.platform !== "darwin") {
  throw new Error("Regenerate the app icon on macOS, where iconutil is available.");
}
const check = args.includes("--check");
const output = fileURLToPath(new URL("../native/Assets/", import.meta.url));
const fish = fishArt(401);
const stroke = 'fill="none" stroke-linecap="round" stroke-linejoin="round"';
const path = (d: string, color: string, width: number, extra = "") =>
  `<path d="${d}" stroke="${color}" stroke-width="${width}" ${stroke} ${extra}/>`;

// Use the same fish paths and palette as the app and website. The inset paper
// tile leaves transparent space for the native icon silhouette and its shadow.
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-labelledby="title">
  <title id="title">chippytea app icon: a golden battered fish on a paper tile</title>
  <!-- Generated by scripts/generate-app-icon.ts. -->
  <defs>
    <filter id="shadow" x="-15%" y="-15%" width="130%" height="140%" color-interpolation-filters="sRGB">
      <feDropShadow dx="0" dy="12" stdDeviation="12" flood-color="${tea.ink}" flood-opacity=".18"/>
    </filter>
    <clipPath id="fish"><path d="${fish.bodyD}"/></clipPath>
  </defs>
  <rect x="96" y="96" width="832" height="832" rx="186" fill="${tea.paper}" filter="url(#shadow)"/>
  <rect x="97" y="97" width="830" height="830" rx="185" fill="none" stroke="${tea.ink}" stroke-opacity=".12" stroke-width="2"/>
  <g transform="translate(140 272) scale(12)">
    ${fish.steam.map((s) => path(s.d, tea.inkSoft, s.width)).join("\n    ")}
    <path d="${fish.bodyD}" fill="${tea.gold}"/>
    ${path(fish.batterD, tea.goldDeep, 0.9, 'clip-path="url(#fish)" opacity=".4"')}
    ${path(fish.bodyD, tea.ink, 1.7)}
    ${fish.details.map((s) => path(s.d, tea.ink, s.width)).join("\n    ")}
    <circle cx="12" cy="22" r="1.8" fill="${tea.ink}"/>
    <circle cx="11.45" cy="21.45" r=".55" fill="${tea.card}"/>
  </g>
</svg>
`;

const scratch = mkdtempSync(join(tmpdir(), "chippytea-app-icon-"));
try {
  const source = join(scratch, "AppIcon.svg");
  const iconset = join(scratch, "AppIcon.iconset");
  const icon = join(scratch, "AppIcon.icns");
  writeFileSync(source, svg);
  mkdirSync(iconset);
  // Each point size has a native 1x and Retina 2x representation, including
  // the 16/32-point sizes used in Finder and System Settings lists.
  for (const size of [16, 32, 128, 256, 512]) {
    for (const scale of [1, 2]) {
      const pixels = String(size * scale);
      const name = `icon_${size}x${size}${scale === 2 ? "@2x" : ""}.png`;
      execFileSync("rsvg-convert", ["--width", pixels, "--height", pixels,
        "--output", join(iconset, name), source], { stdio: "inherit" });
    }
  }
  execFileSync("iconutil", ["--convert", "icns", "--output", icon, iconset], { stdio: "inherit" });

  const files = [["AppIcon.svg", Buffer.from(svg)], ["AppIcon.icns", readFileSync(icon)]] as const;
  if (!check) mkdirSync(output, { recursive: true });
  for (const [name, content] of files) {
    const destination = join(output, name);
    if (check) {
      if (!existsSync(destination) || !readFileSync(destination).equals(content)) {
        throw new Error(`${name} is out of date; run bun scripts/generate-app-icon.ts`);
      }
    } else {
      writeFileSync(destination, content);
    }
  }
  console.log(check ? "App icon is up to date." : "Generated native/Assets/AppIcon.svg and AppIcon.icns.");
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
